twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        name: 'Sfaxi Yassine'
        address: 'Sartrouville'
        email: 'syessine18@gmail.com'
        company: 'SY Production'
        telephone: '06.07'
        siret: '1234567'
        ape: '77'
        tva: 'ART.293B du CGI'
        quantity: '1'
        host: 'ionos'
        domain: 'test.fr'
when@test:
    twig:
        strict_variables: true
